language: cpp

sudo: required
dist: trusty

env:
  global:  
   - GTEST_DIR=${TRAVIS_BUILD_DIR}/gtest

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-3.9
    packages: &native_deps
    - cmake
    - libusb-1.0-0-dev
    - libfftw3-dev
#    - libqt5qml5
    - libgtest-dev
#    - libqt5opengl5-dev
#    - qtbase5-dev
#    - qttools5-dev
#    - qttools5-dev-tools
    - gcc-5
    - g++-5
#    - doxygen
#    - clang-3.6

# We are testing
# * linux with g++5 (and clang 3.6)
# * osx with clang 3.6
matrix:
  include:
    - compiler: gcc
      env: CMAKE_CXX_COMPILER=g++-5
      os: linux
#    - compiler: clang
#      env: CMAKE_CXX_COMPILER=clang++-3.6
#      os: linux
    - compiler: clang
      env: CMAKE_CXX_COMPILER=/usr/bin/clang++
      os: osx
  
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install libusb fftw qt5; export CMAKE_PREFIX_PATH=$(brew --prefix qt5); fi
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo add-apt-repository ppa:beineri/opt-qt542-trusty;sudo apt-get -qq update; sudo apt-get --yes install -qq qt54base; fi

before_script:
    - QTDIR="/opt/qt55"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt54/bin/qt54-env.sh
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH ../

script:
    - make -j4

before_deploy:
    - make package

notifications:
  on_success: change
  on_failure: always

# User "ci-openhantek". Uses a travis encrypted github access token for that user.
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: XGiTAo3bIZXq1gWQQaodllxTX/Wg0Jwgs0Dxtwi688usIlyUheMmmda9Ot9hdrXTlxJJICgUE1RVwjYynE7c7uUKE9E82QlM/E05m+rAYXzCCzOdrkku2C7netAnFs8ZbNlfMn459QOAkPvbF0Wfx1h+pAYxpXbTFl0cwatBxIjVxc4BUpulbY2SJK413mm8nOwfHI/MpBaJwX2A1vaV4IevXWPVnLrypqA2g7B4N9NHnLB/kuBo6nKM9sjOLfvV7Lzmq/S2a9GeDF8JOO3OPjiQVLV+fwQbUn8l4Rfm6vzs1h4MYJ0E7QBV+laLbD3tHic9IcOHReinG64OTiA4uL8W75V556qGme4Eb6TId2SwnNtJPRU5zn5KIB3J6qXSrqA0XiPjm+lyxQF/LB4hIgMtr2r0t3a2+6zSOuu55D4W+IF4S7Q2ogRKyuu9Ku/QXPcmYRZQNkieXNUn7D6dANyQb6ml4uREZPlwHqLnbOi5RMBi5awiYY6NI8DLdcO4NXn+IsaWbJS50GQRGWJs/hB4PWXeuSAkjQ0kenPOf3ZcDhf73ynb/H6Z2gormgAFM91VC8yhvnjm+2zUMm+ChtYzX7xytCt34Itsrv7U+U1OdECMXRZkbbbvebbTeuo2jBqMdKEp4cDCvPEdrXlWwAFL//3sQvf2O23QEFkpTxY=
  file: "packages/OpenHantekProject-*"
  on:
    repo: OpenHantek/openhantek
#    condition: "$CMAKE_CXX_COMPILER = clang++-3.6"
    tags: true
