language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

os:
  - osx
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-3.6
    packages: &native_deps
    - cmake
    - qttools5-dev
    - qttools5-dev-tools
    - libusb-1.0-0-dev
    - libfftw3-dev
    - libqt5qml5
    - doxygen
    - gcc-5
    - g++-5
    - clang-3.6

# We construct a build matrix for two operating systems (linux, osx) and two compilers (gcc, clang)
matrix:
  exclude:
    - os: osx
      compiler:
        - gcc
#  fast_finish: true
  allow_failures:
    - os: osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -qq libqt5opengl5-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install libusb fftw qt5; fi

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "clang" ]]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
    - mkdir build
    - cd build
    - cmake ../

script:
    - make

before_deploy:
    - make package

notifications:
  on_success: change
  on_failure: always

deploy:
  provider: releases
  api_key:
    secure: kIX221nPUe3OM5CNeEJ1iyRg2FFpmlL7c+uxJS11+HBRcFTGCIArHoxMIUb1u289+Co0jp42BVxhpo9PaKhHhzy3iVsKM1xOty3GAr9/1KzVnvJY0dOWqO2cYks4w24WF50ii3kUtYGVKpJrsHPT8UeI2z+taYr1jBmKkoYuoWDG+3CAZytLAsOVDRPylhzSD8B+OrCHIbN1npcitEpFUMJWgvDVi6ZKsz8o6obs/NhwFEc9TBDhS7CeIoAcNt7S0WdDM4ZyHyOeYShWxL0DlZBuhvS7SVZbxy/DS/cTAyoaWqgFLQokmhsKkVIytnq40kC9kGUZvoSpfwtfnA55eElFP5sNbnjQEUaDgq8Doi+aTTc7WRmhBCJbmz6RlqPAECQzx67JuTukV7F6Ds6B34+9naV3dAhj7dnMAoIvY1UK4NhvT+w3aQNR3B93TLZfYHvAmVoZcMGEY/EqLbHdMdJ7E9YGEQQUXW/753EmulCu9/O/gEs+8DlNc1ejFUGJhQmTyJBOLupJpFanC+6mTcbSGlJLwAHxL5yuJ0x5xLzZvJ9jTJI1QFu8ZztFw6gPCBpxPVle6E/Ht3CIByoK5RtKzhJBxgYDG+k0Yaqgbp1wh1ET56xEj8GxQlTKW43Mwbt4aXAarZ11C3erab5lCQyubIUXuq0TWxJLDTfOC6I=
  file:
    - packages/OpenHantek-Release.sh
    - packages/OpenHantek-Release.zip
  on:
    repo: OpenHantek/openhantek