configuration:
  - Release

image:
  - Visual Studio 2015

shallow_clone: true

before_build:
  - set qtpath64="C:\Qt\5.11\msvc2015_64"
  - set arch64=x64
  - set dir64=build_x64

  - md %dir64%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %arch64%
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_PREFIX_PATH=%qtpath64% -DCMAKE_BUILD_TYPE=%configuration% -B%dir64% -H.

  - set qtpath32="C:\Qt\5.11\msvc2015"
  - set arch32=x86
  - set dir32=build_x86

  - md %dir32%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %arch32%
  - cmake -G "Visual Studio 14 2015" -DCMAKE_PREFIX_PATH=%qtpath32% -DCMAKE_BUILD_TYPE=%configuration% -B%dir32% -H.

build_script:
  - cmake --build %dir64% --config %configuration% --target package
  - cmake --build %dir32% --config %configuration% --target package

artifacts:
  - path: $(dir64)\openhantek\$(configuration)
    name: OpenHantek-Win-$(arch64)-$(configuration)-b$(APPVEYOR_BUILD_NUMBER)
  - path: $(dir32)\openhantek\$(configuration)
    name: OpenHantek-Win-$(arch32)-$(configuration)-b$(APPVEYOR_BUILD_NUMBER)

deploy:
  - tag: $(APPVEYOR_REPO_TAG_NAME)
    provider: GitHub
    auth_token:
        secure: 4TSFa7zTbxPVDkS9pGWO0BIPD9r2NnnHGe03pg5rjEuvSH5pntkmMdLM7MePJLma
    artifact: /.*\.zip,.*\.exe/
    draft: true
    prerelease: true
    force_update: true
    on:
      #branch: master                 # release from master branch only
      APPVEYOR_REPO_TAG: true        # deploy on tag push only
